### ISSUE TITLE
Help on duplicate content

### ISSUE THREAD

**Issue by EmmaJLussier** [EmmaJLussier/hear-me-oh-content#1]
@thatkidmadrid @carolsinc

Hey markbot says this, how would I go about fixing this?
![Screen Shot 2021-09-30 at 6 56 37 PM (2)](https://user-images.githubusercontent.com/77282460/135540549-d7cc737b-e0b3-4f63-8438-fff783cfd517.png)
s

**Comment by thatkidmadrid** [comment]
this is probably referring to the `Read more` links

remember what was covered in the videos and earlier in class. There is an attribute you can include to provide more details in the form of a label that the screen reader can use. Please refer to the [Accessibility Cheat Sheet](https://learn-the-web.algonquindesign.ca/topics/accessibility-cheat-sheet/) for more info
